name: Build Me Docker

on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    env:
       TAG: buildme
       USER: frankisinfotech
       PAT: ${{secrets.GITHUB_TOKEN}}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Build Me
      run: |
         docker build -t $TAG .
    - name: GHCR Login
      run: |
         echo $PAT | docker login ghcr.io -u $USER --password-stdin
         docker tag $TAG ghcr.io/$USER/${TAG}:latest
         docker push ghcr.io/$USER/${TAG}:latest
         trivy image ghcr.io/$USER/${TAG}:latest
     
