name: Build Me Docker

on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    env:
       TAG: buildme
       USER: frankisinfotech
       TTY: true

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Build Me
      run: |
         docker build -t $TAG .
    - name: GHCR Login
      run: |
         echo $PAT | docker login ghcr.io -u $USER --password-stdin 
         docker tag $TAG ghcr.io/$USER/${TAG}:latest
         docker push ghcr.io/$USER/${TAG}:latest
         docker scan ghcr.io/$USER/${TAG}:latest
         shell: /usr/bin/bash -e {0}

