name: Build Me Docker

on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Build Me
      run: |
         docker build -t buildme .
