name: Build Me Docker

on: [push]

jobs:
  build_docker:
    runs-on: ubuntu-latest
    env:
       TAG: buildme
       USER: frankisinfotech
       PAT: ${{secrets.GITHUB_TOKEN}}
       REGISTRY: ghcr.io
       IMAGE_NAME: ${{ github.repository }}


    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Build Me
      run: |
         docker build -t $TAG .
    - name: GHCR Login
      run: |
         echo $PAT | docker login ghcr.io -u $USER --password-stdin
         docker tag $TAG ghcr.io/$USER/${TAG}:${{ github.sha }}
         docker push ghcr.io/$USER/${TAG}:${{ github.sha }}
         
    - name: Run static analysis
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.REGISTRY }}/${{ env.USER }}/${{ env.TAG }}:${{ github.sha }}'
#         ghcr.io/$USER/${TAG}:${{ github.sha }}'
        security-checks: 'vuln,secret,config'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-image-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy Image scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: 'trivy-image-results.sarif'
          category: 'image'
