name: Play with Actions

on: [push]

jobs:
   play-with-actions: 
     runs-on: ubuntu-latest
     
     steps:
     - name: Get ENVs
       run: |
         pwd
         echo $GITHUB_SHA;
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
         echo "${{ github.token }}"
         ls -l
   
     - name: Checkout
       run: |
         uses: action/checkout@v1
         ls -l
#        git fetch
