name: Shell Commands

on: [push]

jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
    
    steps:
    - name: List the root filesystem
      run: ls -l
    
    - name: run series of cmds
      run: |
        mkdir frankis
        node -v
        npm -v
        apt install curl 
        curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
        source ~/.bashrc   
        nvm -v
