name: Shell Commands

on: [push]

jobs:
  run-shell-cmd:
    runs-on: ubuntu-latest
    
    steps:
    - name: List the root filesystem
      run: ls -l
    
    - name: run series of cmds
      run: |
        mkdir frankis
        node -v
        shell: bash -l -eo pipefail {0}
        npm ls
